# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('stu_id', models.CharField(max_length=20, unique=True, verbose_name='student ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='phone')),
                ('pay_method', models.CharField(choices=[('ALIPAY', 'Alipay'), ('WECHAT', 'Wechat'), ('QQ', 'QQ')], max_length=30, verbose_name='method of pay')),
                ('alipay', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Alipay account')),
                ('wechat', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='WeChat ID')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='QQ ID')),
                ('nickname', models.CharField(blank=True, max_length=150, null=True, verbose_name='nickname')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=28, verbose_name='balance')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='order title')),
                ('body', models.CharField(max_length=500, verbose_name='order body')),
                ('bounty_size', models.DecimalField(decimal_places=2, max_digits=28, verbose_name='amount of bounty')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('time_modified', models.DateTimeField(auto_now=True, verbose_name='last modified at')),
                ('time_expire', models.DateTimeField(verbose_name='valid before')),
                ('is_taken', models.BooleanField(default=False, verbose_name='is already taken?')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is already completed?')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_made', to='pickup.Fellow', verbose_name='orderer')),
                ('taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_taken', to='pickup.Fellow', verbose_name='order taker')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
