# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('pickup', '0003_auto_20170514_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellow',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='fellow',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='fellow',
            name='is_staff',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether the user can log into this admin site.',
                                      verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
    ]
