# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0004_auto_20170514_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='alipay',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Alipay account'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='pay_method',
            field=models.CharField(choices=[('ALIPAY', 'Alipay'), ('WECHAT', 'Wechat'), ('QQ', 'QQ')], max_length=255, verbose_name='method of pay'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='qq',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='QQ ID'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='stu_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='student ID'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='tel',
            field=models.CharField(max_length=255, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='wechat',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='WeChat ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='order title'),
        ),
    ]
